FROM public.ecr.aws/lambda/python:3.11

WORKDIR /app

COPY requirements_prod.txt .

RUN python -m pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements_prod.txt --target "${LAMBDA_TASK_ROOT}"

COPY app.py ${LAMBDA_TASK_ROOT}

CMD ["app.handler"]