FROM python:3.12-slim

WORKDIR /app

COPY requirements_dev.txt .

RUN python -m pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements_dev.txt

COPY app.py .

EXPOSE 8000

CMD ["python", "app.py"]